# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Words of The Executor'
tagline:          'Diseño, ciencia, juegos y heavy metal'
description:      'El lenguaje del metal desde la perspectiva del diseño y la ingeniería'
url:              http://darkexecutor.github.io
baseurl:          /

author:
  name:           'Simón González Luengo'
  url:            https://twitter.com/darkexecutor

paginate:         3

safe: true
lsi: false

# Custom vars
